spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-store
    username: demo-user
    password: demo-pwd
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

axon:
  eventhandling:
    processors:
      demo:
        threadCount: 2
        initialSegmentCount: 2
        mode: tracking
      DemoSagaProcessor:
        threadCount: 2
        initialSegmentCount: 2
        mode: tracking


